"""
Pipeline module — orchestrates the end-to-end rule generation flow.

Trigger → Generate → Validate → Self-Correct → Output

Implements the core agent loop with configurable retry limits.
"""

from __future__ import annotations

import os
import sys
import json
import logging
import argparse
from pathlib import Path
from typing import Optional

from .trigger import IssueContext, parse_github_issue, parse_description
from .generator import generate_rule, generate_rule_offline
from .validator import validate_rule, ValidationResult

logger = logging.getLogger(__name__)

# Default paths (relative to workspace)
DEFAULT_CAPA_DIR = Path(__file__).parent.parent.parent / "capa"
DEFAULT_RULES_DIR = Path(__file__).parent.parent.parent / "capa-rules"
DEFAULT_LINT_SCRIPT = DEFAULT_CAPA_DIR / "scripts" / "lint.py"
DEFAULT_FORMAT_SCRIPT = DEFAULT_CAPA_DIR / "scripts" / "capafmt.py"


def run_pipeline(
    context: IssueContext,
    max_attempts: int = 3,
    offline: bool = False,
    output_path: Optional[str] = None,
    lint_script: Optional[str] = None,
    format_script: Optional[str] = None,
    rules_dir: Optional[str] = None,
) -> tuple[str, ValidationResult]:
    """
    Run the full agent pipeline: generate → validate → self-correct.

    Args:
        context: Structured issue context
        max_attempts: Maximum generation/correction attempts
        offline: Use offline template generation (no LLM)
        output_path: Path to write the final rule
        lint_script: Path to capa lint.py
        format_script: Path to capa capafmt.py
        rules_dir: Path to capa-rules directory

    Returns:
        Tuple of (final_rule_text, validation_result)
    """
    lint_script = lint_script or str(DEFAULT_LINT_SCRIPT)
    format_script = format_script or str(DEFAULT_FORMAT_SCRIPT)
    rules_dir = rules_dir or str(DEFAULT_RULES_DIR)

    validation_errors: list[str] = []
    best_rule = ""
    best_result = ValidationResult(is_valid=False)

    for attempt in range(1, max_attempts + 1):
        logger.info(f"=== Attempt {attempt}/{max_attempts} ===")

        # Step 1: Generate
        if offline:
            rule_text = generate_rule_offline(context)
        else:
            rule_text = generate_rule(
                context,
                validation_errors=validation_errors if attempt > 1 else None,
            )

        logger.info(f"Generated rule ({len(rule_text)} chars)")

        # Step 2: Validate
        result = validate_rule(
            rule_text,
            rules_dir=rules_dir,
            lint_script=lint_script,
            format_script=format_script,
        )

        # Use formatted version if available
        if result.formatted_rule:
            rule_text = result.formatted_rule

        # Track best attempt
        if result.is_valid or (not best_result.is_valid and result.schema_valid):
            best_rule = rule_text
            best_result = result

        if result.is_valid:
            logger.info(f"✓ Rule passed validation on attempt {attempt}")
            break
        else:
            logger.warning(f"✗ Validation failed on attempt {attempt}:")
            logger.warning(result.error_summary())
            validation_errors = result.errors

    # Step 3: Output
    if output_path:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        Path(output_path).write_text(best_rule)
        logger.info(f"Rule written to {output_path}")

    # Generate PR description
    pr_desc = format_pr_description(context, best_rule, best_result)

    return best_rule, best_result, pr_desc


def format_pr_description(
    context: IssueContext,
    rule_text: str,
    result: ValidationResult,
) -> str:
    """Format a PR description for the generated rule."""
    status = "✅ PASSED" if result.is_valid else "⚠️ NEEDS REVIEW"

    desc = f"""## Auto-generated capa rule

**Source issue:** {context.title}
**Validation status:** {status}

### Rule preview

```yaml
{rule_text.strip()}
```

### Validation details

- YAML syntax: {'✅' if result.yaml_valid else '❌'}
- Schema: {'✅' if result.schema_valid else '❌'}
- Lint: {'✅' if result.lint_passed else '❌'}
"""

    if result.warnings:
        desc += "\n### Warnings\n"
        for w in result.warnings:
            desc += f"- {w}\n"

    if result.errors:
        desc += "\n### Errors\n"
        for e in result.errors:
            desc += f"- {e}\n"

    if context.attck_ids:
        desc += f"\n### ATT&CK Coverage\n"
        for tid in context.attck_ids:
            desc += f"- {tid}\n"

    desc += "\n---\n*Generated by capa-rule-agent (GSoC 2026 PoC)*\n"
    return desc


def main():
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description="capa Rule Generation Agent — generate capa rules from GitHub issues"
    )
    parser.add_argument(
        "--issue-url",
        help="GitHub issue URL to generate a rule for",
    )
    parser.add_argument(
        "--description",
        help="Plain text description of the technique to detect",
    )
    parser.add_argument(
        "--output", "-o",
        help="Output path for the generated rule YAML",
    )
    parser.add_argument(
        "--offline",
        action="store_true",
        help="Use offline template generation (no LLM API call)",
    )
    parser.add_argument(
        "--max-attempts",
        type=int,
        default=3,
        help="Maximum generation attempts (default: 3)",
    )
    parser.add_argument(
        "--lint-script",
        default=str(DEFAULT_LINT_SCRIPT),
        help="Path to capa lint.py script",
    )
    parser.add_argument(
        "--format-script",
        default=str(DEFAULT_FORMAT_SCRIPT),
        help="Path to capa capafmt.py script",
    )
    parser.add_argument(
        "--rules-dir",
        default=str(DEFAULT_RULES_DIR),
        help="Path to capa-rules directory",
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable verbose logging",
    )

    args = parser.parse_args()

    # Set up logging
    log_level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(
        level=log_level,
        format="%(levelname)-8s %(name)s: %(message)s",
    )

    # Parse input
    if args.issue_url:
        context = parse_github_issue(args.issue_url)
    elif args.description:
        context = parse_description(args.description)
    else:
        parser.error("Must provide either --issue-url or --description")

    logger.info(f"Issue context: {context.title}")
    logger.info(f"ATT&CK IDs: {context.attck_ids}")
    logger.info(f"References: {len(context.references)} URLs")

    # Check for API key
    if not args.offline and not os.environ.get("GOOGLE_API_KEY"):
        logger.warning("GOOGLE_API_KEY not set — falling back to offline mode")
        args.offline = True

    # Run pipeline
    rule_text, result, pr_desc = run_pipeline(
        context,
        max_attempts=args.max_attempts,
        offline=args.offline,
        output_path=args.output,
        lint_script=args.lint_script,
        format_script=args.format_script,
        rules_dir=args.rules_dir,
    )

    # Print results
    print("\n" + "=" * 60)
    print("GENERATED RULE")
    print("=" * 60)
    print(rule_text)
    print("=" * 60)
    print(f"Valid: {result.is_valid}")
    if result.errors:
        print(f"Errors: {result.errors}")
    if result.warnings:
        print(f"Warnings: {result.warnings}")

    print("\n" + "=" * 60)
    print("PR DESCRIPTION")
    print("=" * 60)
    print(pr_desc)

    return 0 if result.is_valid else 1


if __name__ == "__main__":
    sys.exit(main())
