"""
PR Workflow module — automates the creation of Pull Requests on mandiant/capa-rules.

Handles the full PR lifecycle:
1. Create a correctly-named branch based on the rule namespace/name
2. Place the rule YAML in the correct directory (matching namespace)
3. Generate a structured PR description with validation results
4. Submit the PR via GitHub CLI (gh) or GitHub API
5. Include test results, ATT&CK coverage, and source issue reference

This module implements the HITL (Human-in-the-Loop) philosophy: the agent
creates the PR, but human maintainers retain control over the final merge.
"""

from __future__ import annotations

import os
import re
import json
import logging
import subprocess
import tempfile
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional

from .trigger import IssueContext
from .validator import ValidationResult

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

@dataclass
class PRContext:
    """All context needed to create a Pull Request."""
    rule_text: str
    rule_name: str
    namespace: str
    issue_number: Optional[int] = None
    attck_ids: list[str] = field(default_factory=list)
    validation_result: Optional[ValidationResult] = None
    test_results: Optional[str] = None
    references: list[str] = field(default_factory=list)
    sample_hashes: list[str] = field(default_factory=list)


@dataclass
class PRResult:
    """Result of PR creation attempt."""
    success: bool
    pr_url: Optional[str] = None
    pr_number: Optional[int] = None
    branch_name: Optional[str] = None
    file_path: Optional[str] = None
    error: Optional[str] = None

    def to_dict(self) -> dict:
        return {
            "success": self.success,
            "pr_url": self.pr_url,
            "pr_number": self.pr_number,
            "branch_name": self.branch_name,
            "file_path": self.file_path,
            "error": self.error,
        }


# ---------------------------------------------------------------------------
# Branch and file path helpers
# ---------------------------------------------------------------------------

def derive_branch_name(rule_name: str, issue_number: Optional[int] = None) -> str:
    """
    Derive a git branch name from the rule name.

    Convention: agent/<namespace-slug>-<issue-number>

    Examples:
        "persist via Windows service" → "agent/persist-via-windows-service-1114"
        "detect BITS usage" → "agent/detect-bits-usage"
    """
    slug = re.sub(r"[^a-z0-9]+", "-", rule_name.lower().strip()).strip("-")
    slug = slug[:50]  # Truncate to reasonable length
    if issue_number:
        return f"agent/{slug}-{issue_number}"
    return f"agent/{slug}"


def derive_file_path(namespace: str, rule_name: str) -> str:
    """
    Derive the file path within capa-rules from namespace and rule name.

    The capa rule file structure mirrors the namespace hierarchy:
        namespace: persistence/service → persistence/service/<rule-name>.yml
        namespace: communication/http → communication/http/<rule-name>.yml

    Examples:
        ("persistence/service", "persist via Windows service")
        → "persistence/service/persist-via-windows-service.yml"
    """
    directory = namespace.replace("/", os.sep)
    filename = re.sub(r"[^a-z0-9]+", "-", rule_name.lower().strip()).strip("-")
    return os.path.join(directory, f"{filename}.yml")


# ---------------------------------------------------------------------------
# PR description generator
# ---------------------------------------------------------------------------

def format_pr_description(ctx: PRContext) -> str:
    """
    Generate a structured PR description following mandiant/capa-rules conventions.

    Includes:
    - Source issue reference
    - Validation results with checkmarks
    - ATT&CK coverage
    - Rule preview in YAML
    - Test results (if available)
    """
    lines = []

    # Header
    lines.append("## Automated capa rule submission")
    lines.append("")
    lines.append(f"Generated by **capa-rule-agent** — an autonomous rule generation pipeline.")
    lines.append("")

    # Source issue
    if ctx.issue_number:
        lines.append(f"**Closes:** #{ctx.issue_number}")
        lines.append("")

    # Validation status
    lines.append("### Validation Results")
    lines.append("")
    if ctx.validation_result:
        vr = ctx.validation_result
        lines.append(f"| Check | Status |")
        lines.append(f"|-------|--------|")
        lines.append(f"| YAML syntax | {'✅ Pass' if vr.yaml_valid else '❌ Fail'} |")
        lines.append(f"| Schema validation | {'✅ Pass' if vr.schema_valid else '❌ Fail'} |")
        lines.append(f"| capa linter | {'✅ Pass' if vr.lint_passed else '❌ Fail'} |")
        lines.append(f"| Overall | {'✅ **PASSED**' if vr.is_valid else '⚠️ **NEEDS REVIEW**'} |")
        lines.append("")

        if vr.warnings:
            lines.append("<details><summary>Warnings</summary>\n")
            for w in vr.warnings:
                lines.append(f"- {w}")
            lines.append("\n</details>\n")

        if vr.errors:
            lines.append("<details><summary>Errors</summary>\n")
            for e in vr.errors:
                lines.append(f"- {e}")
            lines.append("\n</details>\n")
    else:
        lines.append("_Validation not yet run._\n")

    # ATT&CK coverage
    if ctx.attck_ids:
        lines.append("### ATT&CK Coverage")
        lines.append("")
        for tid in ctx.attck_ids:
            lines.append(f"- [{tid}](https://attack.mitre.org/techniques/{tid.replace('.', '/')}/)")
        lines.append("")

    # Rule preview
    lines.append("### Rule Preview")
    lines.append("")
    lines.append("<details><summary>Click to expand YAML</summary>\n")
    lines.append("```yaml")
    lines.append(ctx.rule_text.strip())
    lines.append("```")
    lines.append("\n</details>\n")

    # Test results
    if ctx.test_results:
        lines.append("### Test Results")
        lines.append("")
        lines.append("<details><summary>capa test output</summary>\n")
        lines.append("```")
        lines.append(ctx.test_results)
        lines.append("```")
        lines.append("\n</details>\n")

    # Sample hashes
    if ctx.sample_hashes:
        lines.append("### Samples")
        lines.append("")
        for h in ctx.sample_hashes[:5]:
            lines.append(f"- `{h}`")
        lines.append("")

    # References
    if ctx.references:
        lines.append("### References")
        lines.append("")
        for ref in ctx.references[:5]:
            lines.append(f"- {ref}")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("*This PR was generated by [capa-rule-agent](https://github.com/reyyanxahmed/capa-rule-agent), ")
    lines.append("a GSoC 2026 project for Mandiant FLARE. Human review is required before merging.*")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Git operations
# ---------------------------------------------------------------------------

def _run_git(args: list[str], cwd: str) -> tuple[bool, str]:
    """Run a git command and return (success, output)."""
    try:
        result = subprocess.run(
            ["git"] + args,
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=60,
        )
        output = (result.stdout + result.stderr).strip()
        return result.returncode == 0, output
    except Exception as e:
        return False, str(e)


def _run_gh(args: list[str], cwd: str) -> tuple[bool, str]:
    """Run a GitHub CLI command and return (success, output)."""
    try:
        result = subprocess.run(
            ["gh"] + args,
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=60,
        )
        output = (result.stdout + result.stderr).strip()
        return result.returncode == 0, output
    except Exception as e:
        return False, str(e)


# ---------------------------------------------------------------------------
# PR creation
# ---------------------------------------------------------------------------

def create_pull_request(
    ctx: PRContext,
    rules_repo_dir: Optional[str] = None,
    upstream_repo: str = "mandiant/capa-rules",
    fork_owner: Optional[str] = None,
    dry_run: bool = False,
) -> dict:
    """
    Create a Pull Request on mandiant/capa-rules with the generated rule.

    Workflow:
    1. Create branch from latest master
    2. Write rule file at correct path
    3. Commit with descriptive message
    4. Push to fork
    5. Open PR against upstream

    Args:
        ctx: PRContext with rule and metadata
        rules_repo_dir: Path to local capa-rules clone
        upstream_repo: Upstream repo (default: mandiant/capa-rules)
        fork_owner: Fork owner username (auto-detected from git remote)
        dry_run: If True, prepare everything but don't push or create PR

    Returns:
        Dict with PR result details
    """
    if not rules_repo_dir:
        rules_repo_dir = str(Path(__file__).parent.parent.parent / "capa-rules")

    rules_path = Path(rules_repo_dir)
    if not rules_path.exists():
        return PRResult(
            success=False,
            error=f"Rules repository not found at: {rules_repo_dir}",
        ).to_dict()

    # Step 1: Derive branch and file names
    branch_name = derive_branch_name(ctx.rule_name, ctx.issue_number)
    file_path = derive_file_path(ctx.namespace, ctx.rule_name)
    full_file_path = rules_path / file_path

    logger.info(f"Branch: {branch_name}")
    logger.info(f"File: {file_path}")

    # Step 2: Ensure we're on latest master
    ok, out = _run_git(["fetch", "origin", "master"], cwd=str(rules_path))
    if not ok:
        logger.warning(f"git fetch warning: {out}")

    # Step 3: Create and checkout branch
    ok, out = _run_git(["checkout", "-b", branch_name, "origin/master"], cwd=str(rules_path))
    if not ok:
        # Branch might already exist
        ok, out = _run_git(["checkout", branch_name], cwd=str(rules_path))
        if not ok:
            return PRResult(
                success=False,
                error=f"Failed to create/checkout branch: {out}",
                branch_name=branch_name,
            ).to_dict()

    # Step 4: Write rule file
    full_file_path.parent.mkdir(parents=True, exist_ok=True)
    full_file_path.write_text(ctx.rule_text)
    logger.info(f"Wrote rule to: {full_file_path}")

    # Step 5: Commit
    _run_git(["add", file_path], cwd=str(rules_path))
    commit_msg = f"{ctx.namespace}: add rule '{ctx.rule_name}'"
    if ctx.issue_number:
        commit_msg += f" (fix #{ctx.issue_number})"
    ok, out = _run_git(["commit", "-m", commit_msg], cwd=str(rules_path))
    if not ok:
        return PRResult(
            success=False,
            error=f"Git commit failed: {out}",
            branch_name=branch_name,
            file_path=file_path,
        ).to_dict()

    if dry_run:
        logger.info("Dry run — skipping push and PR creation")
        return PRResult(
            success=True,
            branch_name=branch_name,
            file_path=file_path,
        ).to_dict()

    # Step 6: Push to fork
    ok, out = _run_git(["push", "origin", branch_name], cwd=str(rules_path))
    if not ok:
        return PRResult(
            success=False,
            error=f"Git push failed: {out}",
            branch_name=branch_name,
            file_path=file_path,
        ).to_dict()

    # Step 7: Create PR via gh CLI
    pr_body = format_pr_description(ctx)

    # Write PR body to temp file (to avoid shell escaping issues)
    with tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False) as f:
        f.write(pr_body)
        body_file = f.name

    try:
        # Detect fork owner from git remote
        if not fork_owner:
            ok, remote_url = _run_git(["remote", "get-url", "origin"], cwd=str(rules_path))
            if ok:
                match = re.search(r"github\.com[:/]([^/]+)/", remote_url)
                if match:
                    fork_owner = match.group(1)

        head = f"{fork_owner}:{branch_name}" if fork_owner else branch_name

        pr_title = f"{ctx.namespace}: {ctx.rule_name}"
        if ctx.issue_number:
            pr_title += f" (fix #{ctx.issue_number})"

        gh_args = [
            "pr", "create",
            "--repo", upstream_repo,
            "--head", head,
            "--base", "master",
            "--title", pr_title,
            "--body-file", body_file,
        ]

        ok, out = _run_gh(gh_args, cwd=str(rules_path))
        if ok:
            # Extract PR URL from output
            pr_url = None
            pr_number = None
            for line in out.split("\n"):
                if "github.com" in line and "/pull/" in line:
                    pr_url = line.strip()
                    match = re.search(r"/pull/(\d+)", pr_url)
                    if match:
                        pr_number = int(match.group(1))
                    break

            return PRResult(
                success=True,
                pr_url=pr_url,
                pr_number=pr_number,
                branch_name=branch_name,
                file_path=file_path,
            ).to_dict()
        else:
            return PRResult(
                success=False,
                error=f"gh pr create failed: {out}",
                branch_name=branch_name,
                file_path=file_path,
            ).to_dict()

    finally:
        Path(body_file).unlink(missing_ok=True)
        # Return to previous branch
        _run_git(["checkout", "-"], cwd=str(rules_path))


# ---------------------------------------------------------------------------
# Batch PR creation for proactive pipeline
# ---------------------------------------------------------------------------

def create_batch_prs(
    rules: list[tuple[str, PRContext]],
    rules_repo_dir: str,
    dry_run: bool = False,
) -> list[dict]:
    """
    Create multiple PRs for a batch of generated rules.

    Used by the proactive trigger pipeline to submit rules for
    multiple coverage gaps in one session.

    Args:
        rules: List of (rule_text, PRContext) tuples
        rules_repo_dir: Path to local capa-rules clone
        dry_run: If True, prepare but don't submit

    Returns:
        List of PRResult dicts
    """
    results = []
    for rule_text, ctx in rules:
        ctx.rule_text = rule_text
        logger.info(f"Creating PR for: {ctx.rule_name}")
        result = create_pull_request(
            ctx,
            rules_repo_dir=rules_repo_dir,
            dry_run=dry_run,
        )
        results.append(result)

    success_count = sum(1 for r in results if r.get("success"))
    logger.info(f"Batch PR creation: {success_count}/{len(results)} succeeded")
    return results
